RECEPIES_NAMES = (
    "Spicy Thai Basil Chicken",
    "Creamy Mushroom Risotto",
    "Lemon Garlic Shrimp Pasta",
    "Balsamic Glazed Salmon",
    "Classic Beef Stroganoff",
    "Mediterranean Quinoa Salad",
    "Teriyaki Chicken Skewers",
    "Pumpkin Spice Pancakes",
    "Roasted Vegetable Frittata",
    "Black Bean and Corn Salsa",
    "Chicken Alfredo Pizza",
    "Garlic Parmesan Roasted Brussels Sprouts",
    "Cajun Shrimp and Grits",
    "Caprese Stuffed Chicken",
    "Vegetarian Chili",
    "Honey Mustard Glazed Pork Chops",
    "Greek Orzo Salad",
    "Teriyaki Tofu Stir-Fry",
    "Spinach and Feta Stuffed Mushrooms",
    "Buffalo Chicken Wraps",
    "Pesto Zucchini Noodles",
    "BBQ Pulled Pork Sliders",
    "Butternut Squash Soup",
    "Sushi Bowl",
    "Caramelized Onion and Goat Cheese Tart",
    "Coconut Curry Lentil Soup",
    "Margherita Flatbread",
    "Chipotle Lime Grilled Chicken",
    "Blueberry Almond Smoothie Bowl",
    "Eggplant Parmesan",
    "Teriyaki Salmon Bowls",
    "Avocado Lime Ranch Chicken Salad",
    "Sweet Potato and Black Bean Enchiladas",
    "Lemon Herb Baked Cod",
    "Quinoa Stuffed Bell Peppers",
    "Shrimp Scampi",
    "Greek Yogurt Parfait",
    "Chickpea and Spinach Curry",
    "Hawaiian BBQ Chicken Skewers",
    "Cinnamon Apple Oatmeal",
)